import logging
import os

from dotenv import load_dotenv
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker

load_dotenv()

DB_URL = os.getenv('DB_URL')

engine = create_async_engine(url=DB_URL, echo=False)
async_session_maker = async_sessionmaker(engine, expire_on_commit=False)


logging.basicConfig(level=logging.INFO, datefmt='%(asctime)s', filename='logs.log')
logger = logging.getLogger()

channel_logins = [
    'lh_eex97xothNThi',
    'qwe125412',
    'js9Var2qbq5kODI6',
    'HL12JzSXTAozMjJi',
    'light_almetyevsk',
    'aznakaevo',
    'bugulma',
    'ligth_mendeleevsk',
]
old_channel_logins = [
    'qwe125412'
    , 'khayrullinayrat'
    , 'tsarofkazan'
    , 'qozgin'
    , 'kazan'
    , 'kazanvkp'
    , 'mash_iptash'
    , 'tatarstan_republic'
    , 'typical_kzn'
    , 'tatmediaofficial'
    , 'kzn_xz'
    , 'dirtytatarstan'
    , 'Eduvtatarstan'
    , 'almetyevsk_1'
    , 'city16kazan'
    , 'kazani_chp'
    , 'kazan_da'
    , 'iatatarinform'
    , 'inkazanischa'
    , 'Kazan_ChP_DTP'
    , 'chelnylife'
    , 'video_tatar'
    , 'tatartoday'
    , 'vkazani'
    , 'my_tat'
    , 'kzn_official'
    , 'aida_kazan'
    , 'kznonline'
    , 'newsprotatar'
    , 'shahrikazan'
    , 'intertatgazeta'
    , 'tatar_opershtab'
    , 'kazan_chp116'
    , 'podsluhano_kazan'
    , 'today_kzn'
    , 'kznuniversity'
    , 'kazanfirst'
    , 'ntr24ru'
    , 'bugulma'
    , 'visokaya_gora'
    , 'tnvtv'
    , 'zpravda'
    , 'typicalkzn'
    , 'apparatustatar'
    , 'vgora_vesti'
    , 'kazankstati'
    , 'derbyshki_news'
    , 'almetyevskcity'
    , 'imenno116'
    , 'ideluralnews'
    , 'tatarstan_da'
    , 'kukmor_tatarstan'
    , 'mndnews'
    , 'bugulma_ws'
    , 'nurlatinform'
    , 'novosti_mamadysha'
    , 'sosedi_kazan'
    , 'buinsknews'
    , 'mykazan'
    , 'innopolisnews_rus'
    , 'agr_vesti'
    , 'zainsknews'
    , 'BavlyinformNEWS'
    , 'chistopol_news'
    , 'bugulgazeta'
    , 'tetyushy'
    , 'kazan_novost'
    , 'rtRBC'
    , 'news116ru'
    , 'Tagras_info'
    , 'Aktanysh_Tatarstan'
    , 'kazanalization'
    , 'nemuraviev'
    , 'chakchakbag'
    , 'smi_menzela'
    , 'bikbovguru'
    , 'tatcenter_ru'
    , 'aynuriskhakov'
    , 'eveningkzn'
    , 'kzn_official_tat'
    , 'news_lensk_and_rt_rf'
    , 'now_kazan'
    , 'zeldol'
    , 'novosti_tatarstana1'
    , 'chelny_loc'
    , 'kazan_tat'
    , 'MDK_Tatarstan'
    , 'it_tatarstan'
    , 'iteventsru'
    , 'micrt'
    , 'tatarit'
    , 'tarifirt'
    , 'kazannovostroiki'
    , 'biznesRT'
    , 'dom_pred_fpp_rt'
    , 'business_club_prime_nabchelny'
    , 'tagras_biznesservice'
    , 'gokzn'
    , 'arhitekturasi'
    , 'innoevents'
    , 'SouthWindKazan'
    , 'vishna_kzn'
    , 'events_kazan_best'
    , 'rustamminnikhanov'
    , 'kamil_galeev'
    , 'gazetabo'
    , 'cik_rt'
    , 'ttrstnnws'
    , 'tpolit'
    , 'azatliqradiosi'
    , 'protest_kzn'
    , 'neaysin'
    , 'damir_fattakhov'
    , 'resptatar'
    , 'prokrt'
    , 'y555142'
    , 'Azatliqtatar'
    , 'bdd_agryz'
    , 'Garifullin1'
    , 'yabloko_tat'
    , 'oldkazan'
    , 'dovuziu'
    , 'kazangau'
    , 'millikitaphane'
    , 'milliardtatar'
    , 'KazanNostalgique'
    , 'volleyzenit'
    , 'sportsarae'
    , 'koresh_rt'
    , 'kazandetki'
    , 'suvarstroitt'
    , 'novostroyky'
    , 'Kazan_bezopasno'
    , 'metroelectrotranskzn'
    , 'dps_bugulma'
    , 'gibdd116zelenodolsk'
    , 'zaiyns'
    , 'mendeleevsk_pdd'
    , 'Islam_Tat'
    , 'tatmitropolia'
    , 'Medrese_Fanis_Official'
    , 'FreeTatarstan'
    , 'fpdrt'
    , 'tatarafisha'
    , 'bugulma_online16'
    , 'bugulma_love'
    , 'kazanzdes'
    , 'Tatarstan24TV'
    , 'gazeta_RT'
    , 'chelnynews'
    , 'tatvybory'
    , 'tadza'
    , 'enter_media'
    , 'bykazan'
    , 'gibddtatarstan'
    , 'ShaltayBabay'
    , 'tatmediaofftop'
    , 'kazved'
    , 'ttrstn'
    , 'ipteshler'
    , 'tatarstanza'
    , 'tatnewschelny'
    , 'babaycalls'
    , 'kazangato'
    , 'tatnewstatar'
    , 'bezbuldyrabyz'
    , 'prtatar'
    , 'kznpapa'
    , 'kamil_hazrat'
    , 'aziz_zamaliev'
    , 'phygitaltatarstan'
    , 'podslukzn'
    , 'my_kazan'
    , 'zama_tatarstan'
    , 'myperviekzn'
    , 'mypervie16'
    , 'banana_crypto'
    , 'muhtovinvest'
    , 'nagumanovtd'
    , 'nail_magdeev'
    , 'ramilmullin'
    , 'almet_novosti'
    , 'zama_today'
    , 'chayantatar'
    , 'suumbike'
    , 'tuganaylar2002'
    , 'chelny_news1'
    , 'chelnytv'
    , 'shahrichally'
    , 'mayakonline'
    , 'selskayanovaksubaevo'
    , 'airs16'
    , 'zariaaleks'
    , 'apastovonovosti'
    , 'arskmedia'
    , 'xezmet_gazetasi'
    , 'verhniyuslon'
    , 'drozzanoe90'
    # , 'ElabugaNK'
    # , 'kaibicy'
    # , 'volzhskie'
    # , 'novayakama'
    # , 'len_vesti'
    # , 'shesmauk'
    # , 'pestresy'
    # , 'rusloboda'
    # , 'sabatannars'
    # , 'sarman_rt'
    # , 'bolgarlifenews'
    # , 'TulInformm'
    # , 'n_chrmshn'
    # , 'utazinkaurussu'
    # , 'naBebelya'
    # , 'nkvknew'
    # , 'KRI4yKAZAN'
    # , 'Nizhnekamsk_polit'
    # , 'Nizhnekamskx'
    # , 'rodsovetrt'
]
