version: '3.7'

services:
  app:
    container_name: "NeuroCommenting"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - 'redis:host-gateway'
      - 'mongodb:host-gateway'
      - 'postgresql:host-gateway'