"""remake listen table

Revision ID: 002d0144fdb1
Revises: 77d6c3665d16
Create Date: 2023-12-22 18:13:34.969481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002d0144fdb1'
down_revision: Union[str, None] = '77d6c3665d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_listen_table',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('channel_meta', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('client_id', 'channel_meta', name='listen_client')
    )
    op.drop_table('listen_client_channel_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listen_client_channel_association',
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name='listen_client_channel_association_channel_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='listen_client_channel_association_client_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('client_id', 'channel_id', name='listen_uq_client_channel')
    )
    op.drop_table('client_listen_table')
    # ### end Alembic commands ###
