"""remove unique serial number

Revision ID: 0aea19d5ffb3
Revises: 1176468e7e17
Create Date: 2024-01-15 11:50:54.641289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aea19d5ffb3'
down_revision: Union[str, None] = '1176468e7e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('poem_serial_number_key', 'poem', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('poem_serial_number_key', 'poem', ['serial_number'])
    # ### end Alembic commands ###
