"""add is_tracking

Revision ID: 2168b1cc57de
Revises: fb03274ce235
Create Date: 2023-12-12 13:01:13.456745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2168b1cc57de'
down_revision: Union[str, None] = 'fb03274ce235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel_association', sa.Column('is_tracking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_channel_association', 'is_tracking')
    # ### end Alembic commands ###
