"""add username

Revision ID: 3b1efd0b9151
Revises: 3d7157d7408a
Create Date: 2023-12-19 17:44:39.014943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1efd0b9151'
down_revision: Union[str, None] = '3d7157d7408a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_column('client_channel_association', 'is_tracking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_channel_association', sa.Column('is_tracking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('client', 'username')
    # ### end Alembic commands ###
