"""add is_viewed

Revision ID: 43d8cbfe83fc
Revises: 650b3bee7763
Create Date: 2024-01-12 15:55:44.905789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d8cbfe83fc'
down_revision: Union[str, None] = '650b3bee7763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poem', sa.Column('is_viewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poem', 'is_viewed')
    # ### end Alembic commands ###
