"""add listen relations

Revision ID: 51c36c1edd79
Revises: 00cea89c33f2
Create Date: 2023-12-22 15:19:27.252819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c36c1edd79'
down_revision: Union[str, None] = '00cea89c33f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listen_client_channel_association',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('client_id', 'channel_id', name='listen_uq_client_channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listen_client_channel_association')
    # ### end Alembic commands ###
