"""add role_temperature

Revision ID: 69e7a9c3ae38
Revises: 8ea635494893
Create Date: 2024-01-22 15:23:17.438890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e7a9c3ae38'
down_revision: Union[str, None] = '8ea635494893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('role_temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'role_temperature')
    # ### end Alembic commands ###
