"""empty message

Revision ID: 6bd5b75d0616
Revises: 29c3eb0a6369
Create Date: 2023-11-30 19:17:21.691597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd5b75d0616'
down_revision: Union[str, None] = '29c3eb0a6369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('client_channel_association_client_id_fkey', 'client_channel_association', type_='foreignkey')
    op.drop_constraint('client_channel_association_channel_id_fkey', 'client_channel_association', type_='foreignkey')
    op.create_foreign_key(None, 'client_channel_association', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_channel_association', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_channel_association', type_='foreignkey')
    op.drop_constraint(None, 'client_channel_association', type_='foreignkey')
    op.create_foreign_key('client_channel_association_channel_id_fkey', 'client_channel_association', 'channel', ['channel_id'], ['id'])
    op.create_foreign_key('client_channel_association_client_id_fkey', 'client_channel_association', 'client', ['client_id'], ['id'])
    op.alter_column('client', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channel', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
