"""add is_reacting

Revision ID: 76b15febe244
Revises: abafcdeeb9f1
Create Date: 2024-01-09 13:15:30.912329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b15febe244'
down_revision: Union[str, None] = 'abafcdeeb9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_reacting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'is_reacting')
    # ### end Alembic commands ###
