"""remove joined secondary table

Revision ID: 77d6c3665d16
Revises: d1a57219cc48
Create Date: 2023-12-22 18:08:05.948775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d6c3665d16'
down_revision: Union[str, None] = 'd1a57219cc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_channel_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_channel_association',
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name='client_channel_association_channel_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='client_channel_association_client_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('client_id', 'channel_id', name='uq_client_channel')
    )
    # ### end Alembic commands ###
