"""add comment_communications

Revision ID: 8ea635494893
Revises: f1a212d800cf
Create Date: 2024-01-19 14:50:51.284828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea635494893'
down_revision: Union[str, None] = 'f1a212d800cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('comment_communications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'comment_communications')
    # ### end Alembic commands ###
