"""empty message

Revision ID: 99158877e556
Revises: 6bd5b75d0616
Create Date: 2023-11-30 19:20:48.446176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99158877e556'
down_revision: Union[str, None] = '6bd5b75d0616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_client_channel', 'client_channel_association', ['client_id', 'channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_channel', 'client_channel_association', type_='unique')
    # ### end Alembic commands ###
