"""add non-neuro text

Revision ID: a0598023b928
Revises: 0aea19d5ffb3
Create Date: 2024-01-17 11:59:32.108460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0598023b928'
down_revision: Union[str, None] = '0aea19d5ffb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_neuro', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'text')
    op.drop_column('client', 'is_neuro')
    # ### end Alembic commands ###
