"""add is_premium, send_as

Revision ID: a619e4274e62
Revises: 002d0144fdb1
Create Date: 2023-12-25 13:57:50.253549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a619e4274e62'
down_revision: Union[str, None] = '002d0144fdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('send_as', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'send_as')
    op.drop_column('client', 'is_premium')
    # ### end Alembic commands ###
