"""Add profile info to clients

Revision ID: c0a61a03c174
Revises: 99158877e556
Create Date: 2023-12-07 15:46:11.795936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a61a03c174'
down_revision: Union[str, None] = '99158877e556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('client', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('client', sa.Column('about', sa.String(), nullable=True))
    op.add_column('client', sa.Column('sex', sa.SmallInteger()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'sex')
    op.drop_column('client', 'about')
    op.drop_column('client', 'last_name')
    op.drop_column('client', 'first_name')
    # ### end Alembic commands ###
