"""add photo_path

Revision ID: fb03274ce235
Revises: 2639e12ff29e
Create Date: 2023-12-07 16:04:42.059227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb03274ce235'
down_revision: Union[str, None] = '2639e12ff29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'photo_path')
    # ### end Alembic commands ###
